// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { toast } from "sonner";

const SUPABASE_URL = "https://irgnktjhajerajlsuude.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlyZ25rdGpoYWplcmFqbHN1dWRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzNTE4MjMsImV4cCI6MjA3NDkyNzgyM30.X2N_tJ4DTLZlIgKYIta4l6EJyV6DuxOUQqvnVxD-jAs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: (...args) => {
      return fetch(...args).catch(err => {
        // Handle network errors gracefully
        if (err.message?.includes('net::ERR') || err.name === 'TypeError') {
          toast.error("Koneksi ke server gagal. Periksa koneksi internet Anda atau coba lagi nanti.");
        }
        throw err;
      });
    }
  }
});